[versions]
detekt = "1.23.8"
spring-boot-v3 = "4.0.0"

[libraries]
detekt = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
detekt-libraries = { group = "io.gitlab.arturbosch.detekt", name = "detekt-rules-libraries", version.ref = "detekt" }
spring-boot-v3-dependencies = { group = "org.springframework.boot", name = "spring-boot-dependencies", version.ref = "spring-boot-v3" }
springdoc-openapi-bom = "org.springdoc:springdoc-openapi-bom:3.0.0"
commons-lang3 = "org.apache.commons:commons-lang3:3.20.0"
liquibase-core = "org.liquibase:liquibase-core:5.0.1"
liquibase-sessionlock = "com.github.blagerweij:liquibase-sessionlock:1.6.9"
netty-all = "io.netty:netty-all:4.2.7.Final"
kotlin-logging = "io.github.oshai:kotlin-logging-jvm:7.0.3"

[plugins]
spring-boot-v3 = { id = "org.springframework.boot", version.ref = "spring-boot-v3" }
osdetector = { id = "com.google.osdetector", version = "1.7.3" }
